# -*- coding: utf-8 -*-
"""ASR_Score_Total.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7goAccv2_m8H4yRfZaOFvngzc0PgpP1
"""


import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from scipy.stats import pearsonr, spearmanr
from catboost import CatBoostRegressor
import shap
import matplotlib.pyplot as plt

# ============================================
# CONFIG
# ============================================
SCORES_FILE = "/content/averaged_scores_by_filename.xlsx"
SCORES_SHEET = "averaged_scores"

FLUENCY_FILE = "/content/fluency.csv"
PRON_FILE = "/content/pronunciation.csv"
LEX_SOPH_FILE = "/content/lexical_sophistication.csv"
LEX_DIV_FILE = "/content/lexical_diversity.csv"

N_SPLITS = 5
RANDOM_STATE = 42

# ============================================
# HELPER FUNCTIONS
# ============================================
def round_half(x):
    x = np.asarray(x, dtype=float)
    x = np.clip(x, 0, 9)
    return np.round(x * 2) / 2

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


def safe_corr(func, a, b):
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    if len(np.unique(a)) < 2 or len(np.unique(b)) < 2:
        return np.nan
    return func(a, b)[0]


def qwk_half_band(y_true, y_pred):
    """
    Quadratic Weighted Kappa cho band IELTS 0.0 -> 9.0 step 0.5
    """
    y_true = round_half(y_true)
    y_pred = round_half(y_pred)

    y_true = (y_true * 2).astype(int)
    y_pred = (y_pred * 2).astype(int)

    n = 19  # 0..18
    O = np.zeros((n, n), dtype=float)

    for a, b in zip(y_true, y_pred):
        O[a, b] += 1

    hist_true = np.bincount(y_true, minlength=n)
    hist_pred = np.bincount(y_pred, minlength=n)
    E = np.outer(hist_true, hist_pred) / len(y_true)

    W = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            W[i, j] = ((i - j) ** 2) / ((n - 1) ** 2)

    denom = np.sum(W * E)
    if denom == 0:
        return np.nan

    return 1 - np.sum(W * O) / denom

# ============================================
# 1. LOAD SCORE FILE
# ============================================
score_df = pd.read_excel("averaged_scores_by_filename.xlsx")
score_df["class_name"] = score_df["class_name"].astype(str)
score_df["file_name"] = pd.to_numeric(score_df["file_name"], errors="coerce").astype("Int64")

# ============================================
# 2. LOAD FLUENCY FEATURES
# ============================================
fluency_df = pd.read_csv("fluency.csv")
fluency_df["class_name"] = fluency_df["class_name"].astype(str)

# Tách số file từ cột "file", ví dụ: 1_prob.csv -> 1
fluency_df["file_name"] = (
    fluency_df["file"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)
fluency_df["file_name"] = pd.to_numeric(fluency_df["file_name"], errors="coerce").astype("Int64")

# ============================================
# 3. LOAD LEXICAL DIVERSITY
# ============================================
lex_div_df = pd.read_csv("lexical_diversity.csv")
lex_div_df["class_name"] = lex_div_df["class_name"].astype(str)

# Tách số file từ cột "file", ví dụ 1_prob.csv -> 1
lex_div_df["file_name"] = (
    lex_div_df["file"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)
lex_div_df["file_name"] = pd.to_numeric(lex_div_df["file_name"], errors="coerce").astype("Int64")

# ============================================
# 4. LOAD LEXICAL SOPHISTICATION
# ============================================
lex_soph_df = pd.read_csv("lexical_sophistication.csv")
lex_soph_df["class_name"] = lex_soph_df["class_name"].astype(str)

lex_soph_df["file_name"] = (
    lex_soph_df["file"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)
lex_soph_df["file_name"] = pd.to_numeric(lex_soph_df["file_name"], errors="coerce").astype("Int64")

# ============================================
# 5. MERGE DIVERSITY + SOPHISTICATION
# ============================================
lex_df = lex_div_df.merge(
    lex_soph_df[
        ["class_name", "file_name", "A1", "A2", "B1", "B2", "C1"]
    ],
    on=["class_name", "file_name"],
    how="inner"
)

# ============================================
# 6. LOAD PRONUNCIATION FEATURES
# ============================================
pron_df = pd.read_csv("pronunciation.csv")
pron_df["class_name"] = pron_df["class_name"].astype(str)

# Tách số file từ cột file
# ví dụ: 1_prob.csv -> 1
pron_df["file_name"] = (
    pron_df["file"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)

pron_df["file_name"] = pd.to_numeric(
    pron_df["file_name"],
    errors="coerce"
).astype("Int64")

# ============================================
# 7. MERGE ALL FEATURES → OVERALL DATASET
# ============================================


# merge thêm target vào overall_df
needed_score_cols = [
    "class_name", "file_name",
    "avg_overall",
    "avg_fluency",
    "avg_lexical",
    "avg_pronunciation"
]

overall_df = score_df[needed_score_cols
].merge(
    fluency_df,
    on=["class_name", "file_name"],
    how="inner"
).merge(
    lex_df,
    on=["class_name", "file_name"],
    how="inner"
).merge(
    pron_df,
    on=["class_name", "file_name"],
    how="inner"
)

#print("Số dòng sau merge:", len(overall_df))
print(overall_df.head())


overall_df = overall_df.rename(columns={
    # Fluency
    "total_duration": "flu_total_duration",
    "total_words_x": "flu_total_words",
    "speech_rate_wps": "flu_speech_rate",
    "num_pauses": "flu_num_pauses",
    "duration_pauses": "flu_pause_duration",
    "ratio_pauses_to_duration": "flu_pause_ratio",

    # Lexical
    "TTR": "lex_TTR",
    "MSTTR": "lex_MSTTR",
    "A1" : "lex_A1",
    "A2": "lex_A2",
    "B1": "lex_B1",
    "B2": "lex_B2",
    "C1": "lex_C1",

    # Pronunciation
    "total_words_y": "total_words_pron",
    "0-50%": "pro_0%-50%",
    "50-70%": "pro_50%-70%",
    "70-85%": "pro_70%-85%",
    "85-95%": "pro_85%-95%",
    "95-100%": "pro_95%-100%"
})

# 3. Chọn feature chung
overall_features = [
    # Fluency
    "flu_speech_rate",
    "flu_pause_ratio",

    # Lexical
    "lex_TTR",
    "lex_MSTTR",
    "lex_A1",
    "lex_A2",
    "lex_B1",
    "lex_B2",
    "lex_C1",

    # Pronunciation
    "pro_0%-50%",
    "pro_50%-70%",
    "pro_70%-85%",
    "pro_85%-95%",
    "pro_95%-100%"
]


# ============================================
# 8. TARGETS and  CONVERT FEATURES TO NUMERIC + FILL NA
# ============================================
targets = {
    "overall": "avg_overall",
    "fluency": "avg_fluency",
    "lexical": "avg_lexical",
    "pronunciation": "avg_pronunciation"
}

# convert feature + fill NA
for col in overall_features:
    overall_df[col] = pd.to_numeric(overall_df[col], errors="coerce")
    overall_df[col] = overall_df[col].fillna(overall_df[col].median())

X = overall_df[overall_features]

#print("Tổng số mẫu:", len(overall_df))
#print("Số feature:", len(overall_features))

# ============================================
# 9. 5-FOLD CROSS VALIDATION
# ============================================

kf = KFold(n_splits=5, shuffle=True, random_state=42)

all_metrics = []
all_preds = []

# ============================================
# 10. LISTS FOR OVERALL SHAP ACROSS 5 FOLDS
# ============================================
overall_fold_models = []
overall_shap_values_list = []
overall_X_test_list = []
overall_shap_importance_list = []


# ============================================
# 11. TRAIN CV MODELS FOR 4 TARGETS
# ============================================
for target_name, target_column in targets.items():

    data = overall_df.dropna(subset=[target_column]).copy()

    X_target = data[overall_features]
    y_target = data[target_column]

    maes, rmses, r2s = [], [], []


    for fold, (train_idx, test_idx) in enumerate(kf.split(X_target), 1):

        X_train = X_target.iloc[train_idx]
        X_test = X_target.iloc[test_idx]

        y_train = y_target.iloc[train_idx]
        y_test = y_target.iloc[test_idx]

        model = CatBoostRegressor(
            iterations=300,
            learning_rate=0.05,
            depth=4,
            loss_function="RMSE",
            random_seed=42,
            verbose=False

        )

        model.fit(X_train, y_train)



        y_pred = model.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        r2 = r2_score(y_test, y_pred)

        maes.append(mae)
        rmses.append(rmse)
        r2s.append(r2)

        fold_result = pd.DataFrame({
            "class_name": data.iloc[test_idx]["class_name"].values,
            "file_name": data.iloc[test_idx]["file_name"].values,
            "target": target_name,
            "fold": fold,
            "true_score": y_test.values,
            "pred_score": y_pred
        })

        all_preds.append(fold_result)

        print(
            f"Fold {fold}: "
            f"MAE={mae:.3f} | "
            f"RMSE={rmse:.3f} | "
            f"R2={r2:.3f}"
        )

        # ============================================
        # SAVE SHAP ONLY FOR OVERALL TARGET
        # ============================================
        if target_name == "overall":

            # Lưu model của fold hiện tại
            overall_fold_models.append(model)

            # Tính SHAP trên tập test của fold hiện tại
            explainer = shap.TreeExplainer(model)
            shap_values_fold = explainer.shap_values(X_test)

            # Lưu SHAP values và X_test
            overall_shap_values_list.append(shap_values_fold)
            overall_X_test_list.append(X_test)

            # Tính mean absolute SHAP của từng feature trong fold
            shap_importance_fold = pd.DataFrame({
                "fold": fold,
                "feature": overall_features,
                "mean_abs_shap": np.abs(shap_values_fold).mean(axis=0)
            })

            overall_shap_importance_list.append(shap_importance_fold)

    all_metrics.append({
        "target": target_name,
        "MAE": np.mean(maes),
        "RMSE": np.mean(rmses),
        "R2": np.mean(r2s)
    })

# ============================================
# RESULT
# ============================================

metrics_df = pd.DataFrame(all_metrics)
predictions_df = pd.concat(all_preds, ignore_index=True)

print("\n===== ALL MODEL METRICS =====")
print(metrics_df)


wide_predictions_df = predictions_df.pivot_table(
    index=["file_name"],
    columns="target",
    values=["true_score", "pred_score"],
    aggfunc="first"
)
wide_predictions_df.columns = [
    f"{target}_{score_type}"
    for score_type, target in wide_predictions_df.columns
]

wide_predictions_df = wide_predictions_df.reset_index()

# sắp xếp cột theo đúng thứ tự mong muốn
ordered_cols = [
    "file_name",

    "fluency_pred_score",
    "fluency_true_score",

    "lexical_pred_score",
    "lexical_true_score",

    "pronunciation_pred_score",
    "pronunciation_true_score",

    "overall_pred_score",
    "overall_true_score"
]

wide_predictions_df = wide_predictions_df[ordered_cols]

print("\n===== PREDICTION SAMPLE =====")
print(wide_predictions_df.head(20))

wide_predictions_df.to_csv(
    "catboost_predictions_wide_all_targets.csv",
    index=False,
    encoding="utf-8-sig"
)

# ============================================
# COMBINE OVERALL SHAP VALUES FROM 5 FOLDS
# ============================================

overall_shap_values_cv = np.vstack(overall_shap_values_list)
overall_X_test_cv = pd.concat(overall_X_test_list, axis=0)

# ============================================
# SHAP SUMMARY DOT PLOT - OVERALL CV MODELS
# ============================================

plt.figure(figsize=(10, 7))

shap.summary_plot(
    overall_shap_values_cv,
    overall_X_test_cv,
    feature_names=overall_features,
    show=False,
    max_display=len(overall_features)
)

plt.title(
    "SHAP Summary Plot - Overall Model across 5 CV Folds",
    fontsize=14
)
