"""create user table

Revision ID: 101020db9628
Revises: 
Create Date: 2026-04-24 22:52:30.293400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101020db9628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_submit_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_submit_user_id_user'), type_='foreignkey')

    # ### end Alembic commands ###
